MD013:
  # Number of characters
  line_length: 135
  tables: false
  # Strict length checking
  strict: true
  stern: true
MD004:
  # List style
  style: "consistent"
# MD028/no-blanks-blockquote : Blank line inside blockquote : https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md028.md
MD028: false
# MD024/no-duplicate-heading : Multiple headings with the same content : https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md024.md
MD024:
  allow_different_nesting: true
  # Only check sibling headings
  siblings_only: true
# MD025/single-title/single-h1 : Multiple top-level headings in the same document : https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md025.md
MD025:
  # Heading level
  level: 1
  # RegExp for matching title in front matter
  front_matter_title: ""
MD042: false